search_queries = ["medizin", "chirurgie", "operationsraum", "krankenhaus", "facharzt", "klinik",
	"anatomie", "psychologie", "allgemeinmedizin", "notfallmedizin", "strahlenbehandlung",
	"strahlenschutz", "röntgen", "epidemiologie", "medizinische informatik", "mikrobiologie", 
	"pathologie", "pharmakologie", "unfallchirurgie", "humangenetik", "innere medizin",
	"klinische chemie", "hämatologie", "labormedizin", "transfusionsmedizin", "hämostaseologie",
	"anästhesiologie", "frauenheilkunde", "geburtshilfe", "pathophysiologie", "kinderheilkunde",
	"jugendmedizin", "orthopädie", "physikalische medizin", "infektiologie", "immunologie",
	"rechtsmedizin", "urologie", "radiologie", "augenheilkunde", "dermatologie", "venerologie",
	"hals nasen ohren", "neurologie", "psychiatrie", "psychosomatik", "palliativmedizin",
	"schmerzmedizin", "kardiologie", "onkologie", "bildgebungsverfahren in der radiologie", 
	"interventionelle radiologie", "innere blutungen", "gefäßchirurgie", "endovaskuläre chirurgie", 
	"computertomographie", "magnet resonanz tomographie", "kernspintomographie", "ultraschall",
	"gefäßverschlüsse", "blutungen", "tumoren", "lebersystem", "gallengangsystem", "aortenruptur",
	"aortenaneurysma", "aortendissektion", "darmtrakts", "beckenbodens", "magentrakts", "sonographie",
	"röntgenuntersuchung", "katheter", "röhrchen", "schlauch", "portkatheter", "port-katheter",  
	"portkanüle", "digitale subtraktionsangiographie", "durchleuchtung", "angiographie", 
	"portkathetersystem", "betäubung", "blutkreislauf", "infusion", "gallenwege"]
